version: '3.5'

services:
  db:
    container_name: ${DB_HOSTNAME}
    image: ${DB_IMAGE}
    networks:
      - bza_network
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT_EXT}:${DB_PORT_INT}  
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_vol:/var/lib/postgresql/data

networks:
  bza_network: {}
volumes:
  db_vol: {}