version: '3.5'

services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    hostname: ${DB_CONTAINER_NAME}
    image: ${DB_IMAGE}
    networks:
      - bza-network
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT_EXT}:${DB_PORT_INT}  
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg12_vol:/var/lib/postgresql/data

networks:
  bza-network:
    external: true
volumes:
  pg12_vol: {}